CREATE TABLE WEB_USERS
(
   LOGIN_ID VARCHAR2(20) NOT NULL PRIMARY KEY,
   LOGIN_NAME VARCHAR2(50) NOT NULL,
   LOGIN_PASSWD VARCHAR2(20) NOT NULL,
   LOGIN_ROLE   VARCHAR2(100)
)
/
INSERT INTO WEB_USERS VALUES ('webchart','π‹¿Ì‘±','webchart','EDITOR')
/
COMMIT
/
CREATE TABLE WEB_LOGIN_LOG
(
   ACCESS_TIME DATE DEFAULT SYSDATE,
   CLIENT_IP   VARCHAR2(20) NOT NULL,
   LOGIN_ID    VARCHAR2(20) NOT NULL,
   LOGIN_PASSWD VARCHAR2(20) NOT NULL,
   LOGIN_RESULT VARCHAR2(10) NOT NULL
)
/
CREATE TABLE WEB_SESSION_LOG
(
   SESSIONID  VARCHAR2(64) NOT NULL,
   CLIENT_IP  VARCHAR2(20) NOT NULL,
   LOGIN_ID   VARCHAR2(20) NOT NULL,
   LOGIN_NAME VARCHAR2(20) NOT NULL,
   LOGIN_TIME DATE DEFAULT SYSDATE,
   LOGOUT_TIME DATE,
   LOGOUT_ACTION VARCHAR2(10),
   LOGIN_ROLE VARCHAR2(20)
)
/
CREATE INDEX IND_SESSION_LOG_SID ON WEB_SESSION_LOG(SESSIONID)
/
CREATE TABLE WEB_SESSION
(
   SESSIONID  VARCHAR2(64) NOT NULL,
   CLIENT_IP  VARCHAR2(20) NOT NULL,
   LOGIN_ID   VARCHAR2(20) NOT NULL,
   LOGIN_NAME VARCHAR2(20) NOT NULL,
   LOGIN_TIME DATE DEFAULT SYSDATE,
   LOGIN_ROLE VARCHAR2(20)
)
/
CREATE INDEX IND_SESSION_SID ON WEB_SESSION(SESSIONID)
/
